title: "Sofia's Climate Blog"
author: "SLN"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout


# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50
feed_show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Blog"}
  - {file: "about.md", title: "About"}
  - {title: "Suggestions", url: "https://docs.google.com/forms/d/e/1FAIpQLSeU0cUAkbPayaV9LNJ-lBBxMvwS5XMX7L4nOa6jVF86qJvkeQ/viewform"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:son001@ucsd.edu"}
  - {title: Github, icon: github, url: "https://github.com/symsoph"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

